import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import api from "../../../../services/api/api";

type DocumentRecord = { id: number; title: string; document_type: string; file?: string | null; expiry_date?: string | null; created_at: string };
const records = <T,>(data: T[] | { results?: T[] }) => Array.isArray(data) ? data : data.results ?? [];
function employeeId() { try { return JSON.parse(localStorage.getItem("current_user") ?? localStorage.getItem("user") ?? "{}").employee_id; } catch { return null; } }

export default function MyDocumentsPage() {
  const id = employeeId(); const client = useQueryClient(); const file = useRef<HTMLInputElement>(null);
  const [title, setTitle] = useState(""); const [type, setType] = useState("Personal document"); const [message, setMessage] = useState("");
  const query = useQuery({ queryKey: ["my-documents", id], enabled: Boolean(id), queryFn: async () => records((await api.get<DocumentRecord[] | { results?: DocumentRecord[] }>("/documents/", { params: { employee: id } })).data) });
  const upload = useMutation({ mutationFn: async () => { const selected = file.current?.files?.[0]; if (!id || !title.trim() || !selected) throw new Error("Choose a file and enter a document title."); const body = new FormData(); body.append("employee", String(id)); body.append("title", title.trim()); body.append("document_type", type); body.append("file", selected); await api.post("/documents/", body, { headers: { "Content-Type": "multipart/form-data" } }); }, onSuccess: () => { setTitle(""); if (file.current) file.current.value = ""; setMessage("Document uploaded."); client.invalidateQueries({ queryKey: ["my-documents", id] }); }, onError: (error) => setMessage(error instanceof Error ? error.message : "Could not upload the document.") });
  if (!id) return <main className="dashboard-page"><h1 className="page-title">My documents</h1><p className="alert alert-error">Your account is not linked to an employee profile.</p></main>;
  return <main className="dashboard-page"><header><p className="page-kicker">Employee self-service</p><h1 className="page-title">My documents</h1><p className="page-subtitle">Upload and access documents stored in your employee record.</p></header><section className="panel"><div className="panel-header"><h2 className="panel-title">Upload document</h2></div><form className="panel-body" onSubmit={(e) => { e.preventDefault(); upload.mutate(); }}><div className="form-grid"><label className="field-group">Document title<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label className="field-group">Category<select value={type} onChange={(e) => setType(e.target.value)}><option>Personal document</option><option>Identification</option><option>Certificate</option><option>Tax document</option></select></label><label className="field-group">File<input ref={file} type="file" required /></label></div>{message && <p className="page-subtitle">{message}</p>}<button className="button button-primary" disabled={upload.isPending}>{upload.isPending ? "Uploading…" : "Upload document"}</button></form></section><section className="panel"><div className="panel-header"><h2 className="panel-title">Document library</h2></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Title</th><th>Category</th><th>Uploaded</th><th>File</th></tr></thead><tbody>{query.isLoading ? <tr><td colSpan={4}>Loading documents…</td></tr> : query.data?.length ? query.data.map((doc) => <tr key={doc.id}><td>{doc.title}</td><td>{doc.document_type}</td><td>{new Date(doc.created_at).toLocaleDateString()}</td><td>{doc.file ? <a className="button button-secondary" href={doc.file} target="_blank" rel="noreferrer">Open</a> : "No file"}</td></tr>) : <tr><td colSpan={4}>No documents available.</td></tr>}</tbody></table></div></section></main>;
}
