import { mockCases, mockIncidents } from "../disciplinary-cases/data/mockCases";
import { useState } from "react";

export default function DisciplinaryManagement() {
  const [view, setView] = useState<"All" | "Pending Review" | "Hearing Queue" | "Appealed" | "Closed">("All");
  const [department, setDepartment] = useState("All");
  const resolved = mockIncidents.filter((incident) => incident.outcome === "Resolved Locally").length;
  const records = mockCases.filter((item) => (view === "All" || (view === "Hearing Queue" ? item.status === "Hearing Scheduled" || item.status === "Hearing In Progress" : item.status === view)) && (department === "All" || item.department === department));
  return <div className="dashboard-page"><div><h1 className="page-title">Disciplinary Management</h1><p className="page-subtitle">Governance overview across supervisor-resolved incidents and HR disciplinary cases.</p></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 }}><Metric label="All Incidents" value={mockIncidents.length} /><Metric label="Resolved Locally" value={resolved} /><Metric label="Escalated to HR" value={mockIncidents.length - resolved} /><Metric label="HR Cases" value={mockCases.length} /></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 10 }}>{(["All", "Pending Review", "Hearing Queue", "Appealed", "Closed"] as const).map((item) => <button className="button" key={item} onClick={() => setView(item)} style={{ justifyContent: "center", border: "1px solid var(--border)", background: view === item ? "var(--navy-dark)" : "var(--surface)", color: view === item ? "white" : "var(--ink)", fontWeight: view === item ? 700 : 600 }}>{item === "Hearing Queue" ? "Scheduled / In Progress" : item}</button>)}</div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><select value={department} onChange={(event) => setDepartment(event.target.value)}><option>All departments</option>{[...new Set(mockCases.map((item) => item.department))].map((item) => <option key={item}>{item}</option>)}</select><button className="button button-secondary" onClick={() => alert("Mock Excel report downloaded.")}>Download Excel</button><button className="button button-secondary" onClick={() => alert("Mock PDF report downloaded.")}>Download PDF</button></div><div className="panel"><div className="panel-header"><h2 className="panel-title">Filtered Case Register</h2></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Case</th><th>Employee</th><th>Department</th><th>Status</th><th>Owner</th></tr></thead><tbody>{records.map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.employee}</td><td>{item.department}</td><td>{item.status}</td><td>{item.assignedTo}</td></tr>)}</tbody></table></div></div></div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="summary-card"><div style={{ color: "var(--text-secondary)", fontSize: ".75rem" }}>{label}</div><strong style={{ fontSize: "1.35rem" }}>{value}</strong></div>; }
