# Generated by Django 6.0.7 on 2026-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='to_currency',
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='currency_code',
            field=models.CharField(default='KES', max_length=5),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
