import { useQuery } from "@tanstack/react-query";
import { resources, type ApiRecord } from "@/services/api/resources";

const value = (item: ApiRecord, key: string) => String(item[key] ?? "—");
export default function AttendanceManagementPage() {
  const records = useQuery({ queryKey: ["attendance", "records"], queryFn: () => resources.attendanceRecords.list() });
  const corrections = useQuery({ queryKey: ["attendance", "corrections"], queryFn: () => resources.correctionRequests.list() });
  const error = records.error ?? corrections.error;
  return <main className="dashboard-page"><header><p className="page-kicker">HR operations</p><h1 className="page-title">Attendance management</h1><p className="page-subtitle">Live clock-in/out records submitted by employees from the My Attendance geofenced workflow.</p></header>{error && <p className="alert alert-error">{error.message}</p>}<section className="panel"><div className="panel-header"><h2 className="panel-title">Attendance records</h2></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Date</th><th>Check in</th><th>Check out</th><th>Hours</th><th>Status</th></tr></thead><tbody>{records.isLoading ? <tr><td colSpan={6}>Loading attendance records…</td></tr> : records.data?.length ? records.data.map((item) => <tr key={item.id}><td>{value(item, "employee_name")}</td><td>{value(item, "date")}</td><td>{value(item, "check_in")}</td><td>{value(item, "check_out")}</td><td>{value(item, "hours_worked")}</td><td>{value(item, "status")}</td></tr>) : <tr><td colSpan={6}>No attendance records found.</td></tr>}</tbody></table></div></section><section className="panel"><div className="panel-header"><h2 className="panel-title">Correction requests</h2></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Date</th><th>Reason</th><th>Status</th></tr></thead><tbody>{corrections.isLoading ? <tr><td colSpan={4}>Loading…</td></tr> : corrections.data?.length ? corrections.data.map((item) => <tr key={item.id}><td>{value(item, "employee_name")}</td><td>{value(item, "date")}</td><td>{value(item, "reason")}</td><td>{value(item, "status")}</td></tr>) : <tr><td colSpan={4}>No correction requests.</td></tr>}</tbody></table></div></section></main>;
}
