import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { UserRound, Users, Download } from "lucide-react";
import api from "../../../../services/api/api";

type Employee = { id: number; employee_number: string; full_name: string; work_email: string; personal_email: string; phone_number: string; employment_status: string; employment_type: string; hire_date: string; termination_date?: string | null; branch?: number | null; department?: number | null; designation?: number | null };
const list = <T,>(value: T[] | { results?: T[] }) => Array.isArray(value) ? value : value.results ?? [];
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (char) => char.toUpperCase());

export default function EmployeeLifecyclePage() {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("ALL");
  const [selected, setSelected] = useState<Employee | null>(null);
  const employeesQuery = useQuery({ queryKey: ["lifecycle-employees"], queryFn: async () => list((await api.get<Employee[] | { results?: Employee[] }>("/employees/")).data) });
  const employees = useMemo(() => (employeesQuery.data ?? []).filter((employee) => (status === "ALL" || employee.employment_status === status) && `${employee.full_name} ${employee.employee_number} ${employee.work_email}`.toLowerCase().includes(search.toLowerCase())), [employeesQuery.data, search, status]);
  const distribution = useMemo(() => (employeesQuery.data ?? []).reduce<Record<string, number>>((total, employee) => ({ ...total, [employee.employment_status]: (total[employee.employment_status] ?? 0) + 1 }), {}), [employeesQuery.data]);
  const exportCsv = () => { const rows = ["Employee number,Name,Status,Employment type,Hire date", ...employees.map((employee) => [employee.employee_number, employee.full_name, employee.employment_status, employee.employment_type, employee.hire_date].map((value) => `\"${String(value).replaceAll('\"', '\"\"')}\"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([rows], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "employee-lifecycle.csv"; link.click(); URL.revokeObjectURL(url); };
  return <div className="dashboard-page"><header className="dashboard-heading"><div><p className="page-kicker">People operations</p><h1 className="page-title"><UserRound size={24} /> Employee lifecycle</h1><p className="page-subtitle">Live employment status, tenure, and lifecycle records from the employee directory.</p></div><button className="button button-secondary" onClick={exportCsv}><Download size={16} /> Export CSV</button></header><section className="summary-grid">{Object.entries(distribution).map(([key, value]) => <article className="summary-card" key={key}><span>{label(key)}</span><strong>{value}</strong></article>)}{!Object.keys(distribution).length && <article className="summary-card"><Users size={20} /><span>No employees loaded</span></article>}</section><section className="panel"><div className="panel-header" style={{ display: "flex", gap: 12, flexWrap: "wrap", justifyContent: "space-between" }}><h2 className="panel-title">Employee register</h2><div style={{ display: "flex", gap: 8 }}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employee" /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All lifecycle stages</option>{Object.keys(distribution).map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></div></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Employment type</th><th>Lifecycle stage</th><th>Start date</th><th /></tr></thead><tbody>{employeesQuery.isLoading ? <tr><td colSpan={5}>Loading employee records…</td></tr> : employees.length ? employees.map((employee) => <tr key={employee.id}><td><strong>{employee.full_name}</strong><div>{employee.employee_number} · {employee.work_email || employee.personal_email || "No email"}</div></td><td>{label(employee.employment_type)}</td><td><span className="pill">{label(employee.employment_status)}</span></td><td>{employee.hire_date}</td><td><button className="button button-secondary" onClick={() => setSelected(employee)}>View</button></td></tr>) : <tr><td colSpan={5}>No employees match this view.</td></tr>}</tbody></table></div></section>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><section className="payroll-modal" onClick={(event) => event.stopPropagation()}><div className="payroll-modal-header"><div><p className="page-kicker">{selected.employee_number}</p><h2>{selected.full_name}</h2></div><button className="button button-secondary" onClick={() => setSelected(null)}>Close</button></div><div className="payroll-modal-grid"><div><span>Lifecycle stage</span><strong>{label(selected.employment_status)}</strong></div><div><span>Employment type</span><strong>{label(selected.employment_type)}</strong></div><div><span>Hire date</span><strong>{selected.hire_date}</strong></div><div><span>End date</span><strong>{selected.termination_date ?? "—"}</strong></div></div></section></div>}</div>;
}
