import { Download, RefreshCw, Users, WalletCards, CalendarClock, ClipboardCheck } from "lucide-react";
import { useMemo } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { resources, type ApiRecord } from "../../../../services/api/resources";
import { executiveTheme } from "../../../../theme/executiveTheme";

const text = (item: ApiRecord, key: string) => String(item[key] ?? "—");
const currentBranch = () => { try { return JSON.parse(localStorage.getItem("current_user") ?? localStorage.getItem("user") ?? "{}").branch_name as string | undefined; } catch { return undefined; } };
export default function HrDashboardPage() {
  const client = useQueryClient(); const branchName = currentBranch() ?? "Your branch";
  const employees = useQuery({ queryKey: ["hr", "employees"], queryFn: () => resources.employees.list() }); const payroll = useQuery({ queryKey: ["hr", "payroll"], queryFn: () => resources.payrollRuns.list() }); const leaves = useQuery({ queryKey: ["hr", "leaves"], queryFn: () => resources.leaveRequests.list() }); const attendance = useQuery({ queryKey: ["hr", "attendance"], queryFn: () => resources.attendanceRecords.list() });
  const activeEmployees = useMemo(() => (employees.data ?? []).filter((item) => text(item, "employment_status") === "Active"), [employees.data]); const latestPayroll = payroll.data?.[0]; const pendingLeaves = (leaves.data ?? []).filter((item) => text(item, "status").toLowerCase().includes("pending")); const present = (attendance.data ?? []).filter((item) => ["Present", "Late"].includes(text(item, "status"))).length; const rate = attendance.data?.length ? Math.round(present / attendance.data.length * 100) : 0;
  const exportCsv = () => { const csv = "Metric,Value\nActive employees," + activeEmployees.length + "\nPayroll value," + Number(latestPayroll?.total_gross ?? latestPayroll?.total_cost ?? 0) + "\nPending leave," + pendingLeaves.length + "\nAttendance rate," + rate + "%"; const href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = href; link.download = "hr-dashboard-report.csv"; link.click(); URL.revokeObjectURL(href); };
  const refresh = () => client.invalidateQueries({ queryKey: ["hr"] }); const cards = [{ label: "Active employees", value: activeEmployees.length, icon: Users }, { label: "Latest payroll", value: `KES ${Number(latestPayroll?.total_gross ?? latestPayroll?.total_cost ?? 0).toLocaleString()}`, icon: WalletCards }, { label: "Pending leave", value: pendingLeaves.length, icon: ClipboardCheck }, { label: "Attendance rate", value: `${rate}%`, icon: CalendarClock }];
  return <main className={executiveTheme.page}><div className={executiveTheme.shell}><header className="flex flex-wrap items-end justify-between gap-4"><div><p className={executiveTheme.eyebrow}>HR operations · {branchName}</p><h1 className={executiveTheme.title}>HR dashboard</h1><p className={executiveTheme.subtitle}>Live workforce, payroll, leave and attendance operations for your branch.</p></div><div className="flex gap-2"><button className={executiveTheme.buttonSecondary} onClick={refresh}><RefreshCw size={16}/> Refresh</button><button className={executiveTheme.buttonPrimary} onClick={exportCsv}><Download size={16}/> Export report</button></div></header><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon }) => <article key={label} className={`${executiveTheme.cardSoft} p-5`}><div className="flex justify-between"><p className={executiveTheme.eyebrow}>{label}</p><Icon size={18} className="text-[#c8a45d]"/></div><strong className="mt-3 block text-2xl text-[#fffaf0]">{value}</strong><p className="mt-1 text-xs text-[#8fa0b8]">Live backend data</p></article>)}</section><section className={`${executiveTheme.card} mt-5 overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-bold">Pending leave approvals</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-[#8fa0b8]"><tr><th className="p-4">Employee</th><th>Type</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody>{pendingLeaves.length ? pendingLeaves.map((item) => <tr className="border-t border-white/10" key={item.id}><td className="p-4">{text(item, "employee_name")}</td><td>{text(item, "leave_type_name")}</td><td>{text(item, "start_date")}</td><td>{text(item, "end_date")}</td><td>{text(item, "status")}</td></tr>) : <tr><td className="p-8 text-center text-[#c9d3df]" colSpan={5}>No pending leave requests.</td></tr>}</tbody></table></div></section><section className={`${executiveTheme.card} mt-5 overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-bold">Recent attendance</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-[#8fa0b8]"><tr><th className="p-4">Employee</th><th>Date</th><th>Check in</th><th>Check out</th><th>Status</th></tr></thead><tbody>{(attendance.data ?? []).slice(0, 12).map((item) => <tr className="border-t border-white/10" key={item.id}><td className="p-4">{text(item, "employee_name")}</td><td>{text(item, "date")}</td><td>{text(item, "check_in")}</td><td>{text(item, "check_out")}</td><td>{text(item, "status")}</td></tr>)}</tbody></table></div></section></div></main>;
}
