import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import api from "../../../services/api/api";

type Complaint = { id: number; category: string; subject: string; details: string; preferred_resolution: string; confidentiality: string; attachment?: string | null; status: string; resolution_notes: string; created_at: string };
const list = <T,>(data: T[] | { results?: T[] }) => Array.isArray(data) ? data : data.results ?? [];

export default function ComplaintsPage() {
  const client = useQueryClient(); const attachment = useRef<HTMLInputElement>(null);
  const [form, setForm] = useState({ category: "Workplace concern", subject: "", details: "", preferred_resolution: "Investigation requested", confidentiality: "Standard" }); const [message, setMessage] = useState("");
  const complaints = useQuery({ queryKey: ["complaints"], queryFn: async () => list((await api.get<Complaint[] | { results?: Complaint[] }>("/hr-operations/complaints/")).data) });
  const submit = useMutation({ mutationFn: async () => { if (!form.subject.trim() || !form.details.trim()) throw new Error("Enter a subject and details for your complaint."); const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); const file = attachment.current?.files?.[0]; if (file) body.append("attachment", file); await api.post("/hr-operations/complaints/", body, { headers: { "Content-Type": "multipart/form-data" } }); }, onSuccess: () => { setForm({ category: "Workplace concern", subject: "", details: "", preferred_resolution: "Investigation requested", confidentiality: "Standard" }); if (attachment.current) attachment.current.value = ""; setMessage("Complaint submitted securely."); client.invalidateQueries({ queryKey: ["complaints"] }); }, onError: (error) => setMessage(error instanceof Error ? error.message : "Could not submit the complaint.") });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <main className="dashboard-page"><header><p className="page-kicker">Employee self-service</p><h1 className="page-title">Complaints</h1><p className="page-subtitle">Submit a confidential workplace concern and follow its actual status.</p></header><div className="dashboard-grid two-columns"><section className="panel"><div className="panel-header"><h2 className="panel-title">Submit a complaint</h2></div><form className="panel-body" onSubmit={(event) => { event.preventDefault(); submit.mutate(); }}><div className="form-grid"><label className="field-group">Category<select value={form.category} onChange={(e) => update("category", e.target.value)}><option>Workplace concern</option><option>Facility infrastructure</option><option>Compensation payroll dispute</option><option>Harassment</option></select></label><label className="field-group">Preferred resolution<select value={form.preferred_resolution} onChange={(e) => update("preferred_resolution", e.target.value)}><option>Investigation requested</option><option>Mediation session</option><option>Direct action</option></select></label><label className="field-group">Subject<input required value={form.subject} onChange={(e) => update("subject", e.target.value)} /></label><label className="field-group">Confidentiality<select value={form.confidentiality} onChange={(e) => update("confidentiality", e.target.value)}><option>Standard</option><option>Strictly confidential</option></select></label></div><label className="field-group">Details<textarea required rows={5} value={form.details} onChange={(e) => update("details", e.target.value)} /></label><label className="field-group">Attachment (optional)<input ref={attachment} type="file" /></label>{message && <p className="page-subtitle">{message}</p>}<button className="button button-primary" disabled={submit.isPending}>{submit.isPending ? "Submitting…" : "Submit complaint"}</button></form></section><section className="panel"><div className="panel-header"><h2 className="panel-title">Complaint history</h2></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Subject</th><th>Category</th><th>Submitted</th><th>Status</th><th>Update</th></tr></thead><tbody>{complaints.isLoading ? <tr><td colSpan={5}>Loading complaints…</td></tr> : complaints.data?.length ? complaints.data.map((item) => <tr key={item.id}><td>{item.subject}</td><td>{item.category}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td>{item.status}</td><td>{item.resolution_notes || "No update yet"}</td></tr>) : <tr><td colSpan={5}>No complaints submitted.</td></tr>}</tbody></table></div></section></div></main>;
}
