import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import api from "../../../services/api/api";

type Employee = { id: number; full_name: string; department?: number | null };
type Case = { id: number; employee: number; employee_name: string; incident_date: string; description: string; severity: string; status: string; action_taken: string; hearing_date?: string | null; resolution_notes: string };

const labels: Record<string, string> = { OPEN: "Pending Review", UNDER_INVESTIGATION: "Under Investigation", HEARING_SCHEDULED: "Hearing Scheduled", RESOLVED: "Decision Issued", APPEALED: "Appealed", CLOSED: "Closed" };
const list = <T,>(value: T[] | { results?: T[] }) => Array.isArray(value) ? value : value.results ?? [];

export default function Dashboard() {
  const client = useQueryClient();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  const [selected, setSelected] = useState<Case | null>(null);
  const [form, setForm] = useState({ employee: "", description: "", severity: "MINOR", incident_date: new Date().toISOString().slice(0, 10) });
  const casesQuery = useQuery({ queryKey: ["disciplinary-cases"], queryFn: async () => list((await api.get<Case[] | { results?: Case[] }>("/hr-operations/disciplinary-cases/")).data) });
  const employeesQuery = useQuery({ queryKey: ["disciplinary-employees"], queryFn: async () => list((await api.get<Employee[] | { results?: Employee[] }>("/employees/")).data) });
  const createCase = useMutation({ mutationFn: () => api.post("/hr-operations/disciplinary-cases/", { employee: Number(form.employee), description: form.description, severity: form.severity, incident_date: form.incident_date }), onSuccess: () => { client.invalidateQueries({ queryKey: ["disciplinary-cases"] }); setForm((value) => ({ ...value, employee: "", description: "" })); } });
  const resolveCase = useMutation({ mutationFn: (caseId: number) => api.post(`/hr-operations/disciplinary-cases/${caseId}/resolve/`, { action_taken: "NONE", resolution_notes: "Resolved through the HR case workspace." }), onSuccess: () => { client.invalidateQueries({ queryKey: ["disciplinary-cases"] }); setSelected(null); } });
  const cases = useMemo(() => (casesQuery.data ?? []).filter((item) => (status === "ALL" || item.status === status) && `${item.employee_name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [casesQuery.data, query, status]);
  const openCount = (casesQuery.data ?? []).filter((item) => item.status !== "CLOSED").length;

  return <div className="dashboard-page" style={{ display: "grid", gap: 20 }}>
    <header><p className="page-kicker">People governance</p><h1 className="page-title">Disciplinary cases</h1><p className="page-subtitle">Live HR cases and decisions from the central case register.</p></header>
    <section className="summary-card"><strong style={{ fontSize: "1.6rem" }}>{openCount}</strong><div>Open HR cases</div></section>
    <section className="panel"><div className="panel-header"><h2 className="panel-title">Open a case</h2></div><div className="panel-body" style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))" }}><select value={form.employee} onChange={(event) => setForm({ ...form, employee: event.target.value })}><option value="">Select employee</option>{employeesQuery.data?.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}</option>)}</select><select value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value })}><option value="MINOR">Minor</option><option value="MODERATE">Moderate</option><option value="MAJOR">Major</option><option value="GROSS_MISCONDUCT">Gross misconduct</option></select><input type="date" value={form.incident_date} onChange={(event) => setForm({ ...form, incident_date: event.target.value })} /><textarea style={{ gridColumn: "1 / -1" }} rows={3} value={form.description} placeholder="Describe the allegation and relevant circumstances" onChange={(event) => setForm({ ...form, description: event.target.value })} /><button className="button button-primary" disabled={!form.employee || !form.description || createCase.isPending} onClick={() => createCase.mutate()}>Create case</button>{createCase.isError && <span className="alert alert-error">Could not create the case.</span>}</div></section>
    <section className="panel"><div className="panel-header" style={{ display: "flex", gap: 12, flexWrap: "wrap", justifyContent: "space-between" }}><div><h2 className="panel-title">Case register</h2><p className="page-subtitle">All records are loaded from the HR Operations API.</p></div><div style={{ display: "flex", gap: 8 }}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases" /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div className="panel-body table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Incident</th><th>Severity</th><th>Status</th><th>Action</th></tr></thead><tbody>{casesQuery.isLoading ? <tr><td colSpan={5}>Loading cases…</td></tr> : cases.length ? cases.map((item) => <tr key={item.id}><td>{item.employee_name}</td><td>{item.description}</td><td>{item.severity.replaceAll("_", " ")}</td><td>{labels[item.status] ?? item.status}</td><td><button className="button button-secondary" onClick={() => setSelected(item)}>Open</button></td></tr>) : <tr><td colSpan={5}>No cases match this view.</td></tr>}</tbody></table></div></section>
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><section className="payroll-modal" onClick={(event) => event.stopPropagation()}><div className="payroll-modal-header"><div><p className="page-kicker">Case #{selected.id}</p><h2>{selected.employee_name}</h2></div><button className="button button-secondary" onClick={() => setSelected(null)}>Close</button></div><p><strong>Allegation:</strong> {selected.description}</p><p><strong>Status:</strong> {labels[selected.status] ?? selected.status}</p><p><strong>Incident date:</strong> {selected.incident_date}</p>{selected.status !== "RESOLVED" && selected.status !== "CLOSED" && <button className="button button-primary" disabled={resolveCase.isPending} onClick={() => resolveCase.mutate(selected.id)}>Resolve case</button>}</section></div>}
  </div>;
}
