import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CalendarDays, Check, ChevronRight, ClipboardCheck, Eye, FileText, MessageCircle, Search, Send, Upload, Users, X, type LucideIcon } from "lucide-react";
import { executiveTheme } from "../../../theme/executiveTheme";
import { getCurrentUserRole } from "../../../services/permissions";
import api from "../../../services/api/api";

type Stage = "Submitted" | "Under Review" | "Shortlisted" | "Interview Scheduled" | "Rejected";
type Applicant = { id: string; name: string; email: string; phone: string; role: string; branch: string; submitted: string; stage: Stage; experience: string; education: string; expectedSalary: string; documents: string[]; note?: string };
type ChatMessage = { sender: "assistant" | "user"; text: string };

type RecruitmentApplicationDto = { id: number; reference: string; full_name: string; email: string; phone: string; role: string; branch: string; experience: string; education: string; expected_salary: string; documents: string[]; stage: string; submitted_at: string };
const stageFromApi = (stage: string): Stage => ({ SUBMITTED: "Submitted", UNDER_REVIEW: "Under Review", SHORTLISTED: "Shortlisted", INTERVIEW_SCHEDULED: "Interview Scheduled", REJECTED: "Rejected" }[stage] as Stage | undefined) ?? "Submitted";
const stageToApi = (stage: Stage) => ({ Submitted: "SUBMITTED", "Under Review": "UNDER_REVIEW", Shortlisted: "SHORTLISTED", "Interview Scheduled": "INTERVIEW_SCHEDULED", Rejected: "REJECTED" })[stage];
const fromApi = (item: RecruitmentApplicationDto): Applicant => ({ id: String(item.id), name: item.full_name, email: item.email, phone: item.phone, role: item.role, branch: item.branch, submitted: new Date(item.submitted_at).toLocaleString(), stage: stageFromApi(item.stage), experience: item.experience, education: item.education, expectedSalary: item.expected_salary, documents: item.documents ?? [] });

const stageStyles: Record<Stage, string> = {
  Submitted: "border-slate-400/30 bg-slate-400/10 text-slate-200", "Under Review": "border-[#c8a45d]/30 bg-[#c8a45d]/10 text-[#f1d99b]", Shortlisted: "border-emerald-400/30 bg-emerald-400/10 text-emerald-200", "Interview Scheduled": "border-sky-400/30 bg-sky-400/10 text-sky-200", Rejected: "border-rose-400/30 bg-rose-400/10 text-rose-200",
};

export default function CandidateApplicationsPage() {
  const role = getCurrentUserRole();
  const canDecide = role !== "Manager";
  const [applicants, setApplicants] = useState<Applicant[]>([]);
  const [filter, setFilter] = useState<Stage | "All">("All");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Applicant | null>(null);
  const [decision, setDecision] = useState<{ applicant: Applicant; stage: "Shortlisted" | "Rejected" } | null>(null);
  const [candidateView, setCandidateView] = useState(false);
  const [linkMessage, setLinkMessage] = useState("");
  const visible = useMemo(() => applicants.filter((a) => (filter === "All" || a.stage === filter) && `${a.name} ${a.id} ${a.role}`.toLowerCase().includes(query.toLowerCase())), [applicants, filter, query]);
  useEffect(() => { api.get<RecruitmentApplicationDto[]>("/hr-operations/recruitment-applications/").then(({ data }) => setApplicants(data.map(fromApi))).catch(() => setLinkMessage("Could not load recruitment applications.")); }, []);
  const updateApplicant = async (id: string, stage: Stage, note?: string) => { try { await api.post(`/hr-operations/recruitment-applications/${id}/decide/`, { stage: stageToApi(stage), decision_note: note }); setApplicants((current) => current.map((a) => a.id === id ? { ...a, stage, note } : a)); setLinkMessage("Application decision saved."); } catch { setLinkMessage("Could not save the application decision."); } finally { setDecision(null); setSelected(null); } };
  const counts = { total: applicants.length, review: applicants.filter((a) => a.stage === "Under Review").length, shortlisted: applicants.filter((a) => a.stage === "Shortlisted").length, interviews: applicants.filter((a) => a.stage === "Interview Scheduled").length };
  const summaryCards: Array<[string, number, LucideIcon]> = [["Total applications", counts.total, Users], ["Ready for review", counts.review, ClipboardCheck], ["Shortlisted", counts.shortlisted, Check], ["Interviews booked", counts.interviews, CalendarDays]];

  if (candidateView) return <CandidatePortal onBack={() => setCandidateView(false)} />;
  return <div className={`${executiveTheme.page} candidate-executive-page`}><div className={executiveTheme.shell}>
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className={executiveTheme.eyebrow}>Recruitment · candidate applications</p><h1 className={executiveTheme.title}>Candidate application & shortlisting</h1><p className={executiveTheme.subtitle}>Review role applications, make defensible shortlisting decisions, and smoothly hand successful candidates into onboarding.</p>{linkMessage && <p className="mt-2 text-sm text-emerald-700">{linkMessage}</p>}</div><div className="flex flex-wrap gap-2"><button className={executiveTheme.buttonSecondary} onClick={() => setCandidateView(true)}><Eye size={16} /> Preview candidate portal</button><button className={executiveTheme.buttonPrimary} onClick={async () => { const link = `${window.location.origin}/apply/branch-operations-officer`; try { await navigator.clipboard.writeText(link); setLinkMessage("Application link copied to clipboard."); } catch { setLinkMessage(`Application link: ${link}`); } }}><Send size={16} /> Copy application link</button></div></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summaryCards.map(([label, value, Icon]) => <article key={label} className={`${executiveTheme.cardSoft} p-5`}><div className="flex items-center justify-between"><p className={executiveTheme.eyebrow}>{label}</p><Icon size={18} className="text-[#c8a45d]" /></div><strong className="mt-3 block text-3xl text-[#fffaf0]">{value}</strong><p className="mt-1 text-xs text-[#8fa0b8]">Branch Operations Officer · Nairobi Central</p></article>)}</section>
    <section className={`${executiveTheme.card} overflow-hidden`}><div className="flex flex-col gap-4 border-b border-white/10 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-bold text-[#fffaf0]">Applications received</h2><p className="mt-1 text-sm text-[#c9d3df]">{canDecide ? "Select any candidate to review their profile and supporting documents." : "Your Branch Manager view is read-only; add feedback through the candidate review notes."}</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 text-[#8fa0b8]" size={16}/><input className={`${executiveTheme.input} pl-9`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search applications" /></div><select className={executiveTheme.input} value={filter} onChange={(e) => setFilter(e.target.value as Stage | "All")}>{["All", "Submitted", "Under Review", "Shortlisted", "Interview Scheduled", "Rejected"].map((s) => <option key={s}>{s}</option>)}</select></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-wider text-[#8fa0b8]"><tr><th className="p-4">Candidate</th><th>Role / branch</th><th>Submitted</th><th>Status</th><th className="text-right">Action</th></tr></thead><tbody>{visible.map((applicant) => <tr key={applicant.id} className="border-t border-white/5 text-[#d7e0ec]"><td className="p-4"><p className="font-bold text-[#fffaf0]">{applicant.name}</p><p className="mt-1 text-xs text-[#8fa0b8]">{applicant.id} · {applicant.email}</p></td><td>{applicant.role}<p className="mt-1 text-xs text-[#8fa0b8]">{applicant.branch}</p></td><td>{applicant.submitted}</td><td><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${stageStyles[applicant.stage]}`}>{applicant.stage}</span></td><td className="p-4 text-right"><button className={executiveTheme.buttonSecondary} onClick={() => setSelected(applicant)}>Review <ChevronRight size={15}/></button></td></tr>)}{visible.length === 0 && <tr><td colSpan={5} className="p-10 text-center text-[#c9d3df]">No applications match this view.</td></tr>}</tbody></table></div></section>
  </div><RecruitmentAssistant applicants={applicants} />{selected && <ApplicantModal applicant={selected} canDecide={canDecide} onClose={() => setSelected(null)} onDecision={(stage) => setDecision({ applicant: selected, stage })} />}{decision && <DecisionModal decision={decision} onClose={() => setDecision(null)} onConfirm={(note) => { void updateApplicant(decision.applicant.id, decision.stage, note); }} />}</div>;
}

function ApplicantModal({ applicant, canDecide, onClose, onDecision }: { applicant: Applicant; canDecide: boolean; onClose: () => void; onDecision: (stage: "Shortlisted" | "Rejected") => void }) { return <Modal><div className="flex items-start justify-between"><div><p className={executiveTheme.eyebrow}>{applicant.id}</p><h2 className="text-2xl font-bold">{applicant.name}</h2><p className="mt-1 text-sm text-[#c9d3df]">{applicant.role} · {applicant.branch}</p></div><Close onClick={onClose}/></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Email" value={applicant.email}/><Info label="Phone" value={applicant.phone}/><Info label="Education" value={applicant.education}/><Info label="Expected salary" value={applicant.expectedSalary}/></div><section className={`${executiveTheme.cardSoft} mt-5 p-4`}><p className={executiveTheme.eyebrow}>Experience</p><p className="mt-2 text-sm text-[#d7e0ec]">{applicant.experience}</p></section><section className="mt-5"><p className={executiveTheme.eyebrow}>Supporting documents</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{applicant.documents.map((doc) => <button key={doc} className={`${executiveTheme.cardSoft} flex items-center gap-3 p-3 text-left text-sm text-[#f8f4ea]`}><FileText size={18} className="text-[#c8a45d]"/><span>{doc}</span><Eye size={15} className="ml-auto text-[#8fa0b8]"/></button>)}</div></section>{canDecide && <div className="mt-6 flex flex-wrap justify-end gap-2"><button className={executiveTheme.dangerButton} onClick={() => onDecision("Rejected")}>Reject candidate</button><button className={executiveTheme.buttonPrimary} onClick={() => onDecision("Shortlisted")}><Check size={16}/> Shortlist candidate</button></div>}</Modal>; }
function DecisionModal({ decision, onClose, onConfirm }: { decision: { applicant: Applicant; stage: "Shortlisted" | "Rejected" }; onClose: () => void; onConfirm: (note: string) => void }) { const [note, setNote] = useState(""); const shortlisted = decision.stage === "Shortlisted"; return <Modal><div className="flex justify-between"><div><p className={executiveTheme.eyebrow}>Confirm decision</p><h2 className="text-xl font-bold">{shortlisted ? "Shortlist" : "Reject"} {decision.applicant.name}?</h2></div><Close onClick={onClose}/></div><p className="mt-3 text-sm text-[#c9d3df]">{shortlisted ? "A secure Candidate Portal account and shortlist notification will be queued for this applicant." : "The applicant will receive the automatic outcome message when this hiring round is finalized."}</p><label className="mt-5 block text-sm font-semibold">Internal note <span className="font-normal text-[#8fa0b8]">(optional)</span><textarea className={`${executiveTheme.input} mt-2 min-h-28 w-full`} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add context for the hiring team…"/></label><div className="mt-5 flex justify-end gap-2"><button className={executiveTheme.buttonSecondary} onClick={onClose}>Cancel</button><button className={shortlisted ? executiveTheme.buttonPrimary : executiveTheme.dangerButton} onClick={() => onConfirm(note)}>Confirm {shortlisted ? "shortlist" : "rejection"}</button></div></Modal>; }

function CandidatePortal({ onBack }: { onBack: () => void }) { const [uploaded, setUploaded] = useState<string[]>([]); const steps = ["Application submitted", "Under review", "Shortlisted", "Interview scheduled", "Offer / hired"]; return <div className={`${executiveTheme.page} candidate-executive-page`}><div className={executiveTheme.shell}><header className="flex items-end justify-between"><div><p className={executiveTheme.eyebrow}>Candidate portal</p><h1 className={executiveTheme.title}>Candidate workspace</h1><p className={executiveTheme.subtitle}>Your application status and requested documents are managed by the recruitment team.</p></div><button className={executiveTheme.buttonSecondary} onClick={onBack}>Back to HR review</button></header><section className={`${executiveTheme.card} ${executiveTheme.panelPad}`}><p className={executiveTheme.eyebrow}>Application status</p><div className="mt-5 grid gap-4 md:grid-cols-5">{steps.map((step, index) => <div key={step} className="relative"><div className={`flex h-9 w-9 items-center justify-center rounded-full border ${index === 0 ? "border-[#c8a45d] bg-[#c8a45d] text-[#111827]" : "border-white/15 bg-white/5 text-[#8fa0b8]"}`}>{index === 0 ? <Check size={17}/> : index + 1}</div><p className={`mt-2 text-sm font-semibold ${index === 0 ? "text-[#f1d99b]" : "text-[#8fa0b8]"}`}>{step}</p></div>)}</div></section><section className={`${executiveTheme.card} ${executiveTheme.panelPad}`}><p className={executiveTheme.eyebrow}>Requested documents</p><h2 className="mt-1 text-xl font-bold">Add supporting files</h2><label className={`${executiveTheme.buttonPrimary} mt-4 cursor-pointer`}><Upload size={16}/> Select document<input className="hidden" type="file" onChange={(e) => e.target.files?.[0] && setUploaded((files) => [...files, e.target.files![0].name])}/></label>{uploaded.map((file) => <p key={file} className="mt-3 flex items-center gap-2 text-sm text-emerald-200"><Check size={15}/> {file} selected</p>)}</section></div><RecruitmentAssistant applicants={[]} candidate /></div>; }
function RecruitmentAssistant({ applicants, candidate = false }: { applicants: Applicant[]; candidate?: boolean }) { const [open, setOpen] = useState(false); const [draft, setDraft] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([]); const ask = (question = draft) => { const text = question.trim(); if (!text) return; const lower = text.toLowerCase(); const answer = candidate ? (lower.includes("interview") ? "Your interview is not scheduled yet. We’ll post the confirmed time, location or meeting link in this portal and email you." : "Your application is shortlisted. You can upload requested documents here; only the recruitment team can view them.") : (lower.includes("review") ? `${applicants.filter((a) => a.stage === "Under Review").length} application${applicants.filter((a) => a.stage === "Under Review").length === 1 ? " is" : "s are"} waiting for review.` : lower.includes("shortlist") ? `${applicants.filter((a) => a.stage === "Shortlisted").length} candidates are shortlisted; shortlisting provisions their Candidate Portal access.` : `This recruitment workspace contains ${applicants.length} applications for Nairobi Central. I can help find review queues, shortlisted candidates, and upcoming interviews.`); setMessages((m) => [...m, { sender: "user", text }, { sender: "assistant", text: answer }]); setDraft(""); setOpen(true); }; return <div className="fixed bottom-5 right-5 z-50">{open && <div className="mb-3 w-[min(380px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-white/10 bg-[#101b2c] shadow-2xl shadow-black/40"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><p className="font-bold">Recruitment assistant</p><p className="text-xs text-[#c8a45d]">Scoped to {candidate ? "your candidate portal" : "application data"}</p></div><Close onClick={() => setOpen(false)}/></div><div className="max-h-64 space-y-3 overflow-y-auto p-4">{messages.length ? messages.map((m, i) => <div key={i} className={m.sender === "user" ? "text-right" : "text-left"}><span className={`inline-block max-w-[85%] rounded-2xl px-3 py-2 text-sm ${m.sender === "user" ? "bg-[#c8a45d] text-[#111827]" : "bg-white/10 text-[#f8f4ea]"}`}>{m.text}</span></div>) : <p className="text-sm text-[#c9d3df]">Ask about your recruitment status or next steps.</p>}</div><div className="flex gap-2 border-t border-white/10 p-3"><input className={`${executiveTheme.input} min-w-0 flex-1`} value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => e.key === "Enter" && ask()} placeholder="Ask recruitment assistant…"/><button className={executiveTheme.buttonPrimary} onClick={() => ask()}><Send size={16}/></button></div></div>}<button className="flex h-14 w-14 items-center justify-center rounded-full bg-[#c8a45d] text-[#111827] shadow-2xl" onClick={() => setOpen(!open)} aria-label="Open recruitment assistant"><MessageCircle size={24}/></button></div>; }
function Modal({ children }: { children: React.ReactNode }) { return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-4"><div className={`${executiveTheme.card} max-h-[90vh] w-full max-w-2xl overflow-y-auto p-5 lg:p-6`}>{children}</div></div>; }
function Close({ onClick }: { onClick: () => void }) { return <button className="rounded-lg p-2 text-[#c9d3df] hover:bg-white/10" onClick={onClick} aria-label="Close"><X size={18}/></button>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className={executiveTheme.eyebrow}>{label}</p><p className="mt-1 text-sm text-[#f8f4ea]">{value}</p></div>; }
