# Generated by Django 6.0.7 on 2026-07-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Fixed-Term', 'Fixed-Term'), ('Probation', 'Probation'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Permanent', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated'), ('Renewed', 'Renewed')], default='Active', max_length=20)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('terms', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('new_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reason', models.TextField(blank=True)),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.contract')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_renewals', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('Resignation', 'Resignation'), ('Dismissal', 'Dismissal'), ('Redundancy', 'Redundancy'), ('Retirement', 'Retirement'), ('Mutual', 'Mutual')], max_length=30)),
                ('termination_date', models.DateField()),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('final_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='contracts.contract')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_terminations', to='employees.employee')),
            ],
        ),
    ]
